name: Build RiderLink

on:
  push:
    branches: [ net202 ]
  pull_request:
    branches: [ net202 ]

jobs:
  build:
    env:
      working-dir: ${{ github.workspace}}${{ matrix.config.SEP }}rd-cpp
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest", artifact: "UnrealLink-2020.2.${{ github.run_number }}.zip",
            os: windows-latest,
            SEP: \
          }

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
